name: 稳定版

on:
  schedule:
    - cron: '0 3,20 * * *'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai

#设置仓库的读写权限
permissions:
  contents: write
  actions: write
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.getversion.outputs.tag }}
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      - name: Get version
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r '.tag_name'`
          #tag=`curl https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r '.tag_name' | tr -d 'v'`
          tag=`curl https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name'`
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT
      - name: delete-workflow
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 0

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.tag != needs.check.outputs.cver }}
    steps:
      - name: 获取最新Go
        run: |
          latest_version=$(curl -L -k -s https://golang.org/dl/?mode=json | grep -m 1 -o '"version": "[^"]*' | sed 's/"version": "//' | tr -d 'go" ')
          echo "go版本=$latest_version"
          echo "gotag=$latest_version" >> $GITHUB_ENV
      - name: 安装go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.gotag }}
          # ${{ env.gotag }}
      - name: 安装 UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: v4.2.4
          install-only: true
      - name: Checkout
        uses: actions/checkout@v4
      - name: 编译
        run: |
          git clone https://github.com/tailscale/tailscale -b ${{ needs.check.outputs.ver }} /opt/src
          cd /opt/src
          sudo timedatectl set-timezone "Asia/Shanghai"
          
          # 修改go版本为 1.25 因为自从1.26开始不支持mispel了
          # sed -i 's/^go .*/go 1.25/' go.mod
          go mod tidy
          
          #sed -i 's|return strings.TrimSpace(tailscaleroot.VersionDotTxt) + "-ERR-BuildInfo"|return strings.TrimSpace(tailscaleroot.VersionDotTxt)|g' ./version/version.go
          #sed -i 's|return fmt.Sprintf("%s-dev%s-t%s%s", strings.TrimSpace(tailscaleroot.VersionDotTxt), bi.commitDate, bi.commitAbbrev(), dirtyString())|return fmt.Sprintf(strings.TrimSpace(tailscaleroot.VersionDotTxt))|g' ./version/version.go
          sed -i 's|return strings.TrimSpace(tailscaleroot.VersionDotTxt) + "-dev" + bi.commitDate|return strings.TrimSpace(tailscaleroot.VersionDotTxt)|g' ./version/version.go
          sed -i 's|return "/var/lib/tailscale/tailscaled.state"|return "/etc/storage/tailscale/lib/tailscaled.state"|g' ./paths/paths_unix.go
          #sed -i '/hi.ServerName != m.hostname/,+2d' cmd/derper/cert.go || true

          echo 正常编译
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-X 'tailscale.com/version.longStamp=${{ needs.check.outputs.ver }}' -X 'tailscale.com/version.shortStamp=${{ needs.check.outputs.ver }}' -s -w" tailscale.com/cmd/tailscale
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-X 'tailscale.com/version.longStamp=${{ needs.check.outputs.ver }}' -X 'tailscale.com/version.shortStamp=${{ needs.check.outputs.ver }}' -s -w" tailscale.com/cmd/tailscaled
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -ldflags="-X 'tailscale.com/version.longStamp=${{ needs.check.outputs.ver }}' -X 'tailscale.com/version.shortStamp=${{ needs.check.outputs.ver }}' -s -w" tailscale.com/cmd/derper
          mkdir -p /opt/tainomal
          cp -rf tailscale /opt/tainomal/tailscale
          cp -rf tailscaled /opt/tainomal/tailscaled
          cp -rf derper /opt/tainomal/derper
          cd /opt/tainomal
          upx --lzma --best tailscale
          upx --lzma --best tailscaled
          upx --lzma --best derper
          echo $(md5sum tailscale | awk '{print $1;}') >tailscale.txt
          echo $(md5sum tailscaled | awk '{print $1;}') >tailscaled.txt
          echo $(md5sum derper | awk '{print $1;}') >derper.txt
          cd /opt/src
          echo 编译迷你版
          go clean
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -o tailscaled.combined -tags ts_include_cli -ldflags="-X 'tailscale.com/version.Long=${{ needs.check.outputs.ver }}' -X 'tailscale.com/version.Short=${{ needs.check.outputs.ver }}' -s -w" ./cmd/tailscaled
          mkdir -p /opt/taifull
          cp -rf tailscaled.combined /opt/taifull/tailscaled_full
          cd /opt/taifull
          upx --lzma --best tailscaled_full
          echo $(md5sum tailscaled_full | awk '{print $1;}') >tailscaled_full.txt
          cd /opt/src
          go clean
          echo 编译精简版
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -o tailscale -tags ts_omit_aws,ts_omit_bird,ts_omit_tap,ts_omit_kube,ts_omit_completion,ts_omit_ssh,ts_omit_wakeonlan,ts_omit_capture -ldflags="-X 'tailscale.com/version.Long=${{ needs.check.outputs.ver }}' -X 'tailscale.com/version.Short=${{ needs.check.outputs.ver }}' -s -w" ./cmd/tailscale
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -o tailscaled -tags ts_omit_aws,ts_omit_bird,ts_omit_tap,ts_omit_kube,ts_omit_completion,ts_omit_ssh,ts_omit_wakeonlan,ts_omit_capture -ldflags="-X 'tailscale.com/version.Long=${{ needs.check.outputs.ver }}' -X 'tailscale.com/version.Short=${{ needs.check.outputs.ver }}' -s -w" ./cmd/tailscaled
          mkdir -p /opt/tailite
          cp -rf tailscaled /opt/tailite/tailscaled_lite
          cp -rf tailscale /opt/tailite/tailscale_lite
          cd /opt/tailite
          upx --lzma --best tailscale_lite
          upx --lzma --best tailscaled_lite
          echo $(md5sum tailscale_lite | awk '{print $1;}') >tailscale_lite.txt
          echo $(md5sum tailscaled_lite | awk '{print $1;}') >tailscaled_lite.txt
          echo "build_time=$(TZ=UTC-8 date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV
      - name: 设置机器人
        run : |
         git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
         git config --global user.name "github-actions[bot]"
         sudo timedatectl set-timezone "Asia/Shanghai"
      - name: 上传
        run: |
          [ ! -d "install/${{ needs.check.outputs.tag }}" ] && mkdir -p "install/${{ needs.check.outputs.tag }}"
          cp -rf /opt/tainomal/tailscale "install/${{ needs.check.outputs.tag }}/tailscale"
          cp -rf /opt/tainomal/tailscaled "install/${{ needs.check.outputs.tag }}/tailscaled"
          cp -rf /opt/tainomal/derper "install/${{ needs.check.outputs.tag }}/derper"
          cp -rf /opt/tainomal/derper.txt "install/${{ needs.check.outputs.tag }}/derper.txt"
          cp -rf /opt/tainomal/tailscale.txt "install/${{ needs.check.outputs.tag }}/tailscale.txt"
          cp -rf /opt/tainomal/tailscaled.txt "install/${{ needs.check.outputs.tag }}/tailscaled.txt"
          cp -rf /opt/taifull/tailscaled_full "install/${{ needs.check.outputs.tag }}/tailscaled_full"
          cp -rf /opt/taifull/tailscaled_full.txt "install/${{ needs.check.outputs.tag }}/tailscaled_full.txt"
          cp -rf /opt/tailite/tailscale_lite "install/${{ needs.check.outputs.tag }}/tailscale_lite"
          cp -rf /opt/tailite/tailscaled_lite "install/${{ needs.check.outputs.tag }}/tailscaled_lite"
          cp -rf /opt/tailite/tailscale_lite.txt "install/${{ needs.check.outputs.tag }}/tailscale_lite.txt"
          cp -rf /opt/tailite/tailscaled_lite.txt "install/${{ needs.check.outputs.tag }}/tailscaled_lite.txt"
          git add .
          git commit -am "稳定版：${{ needs.check.outputs.tag }} 更新时间： $(date '+%Y-%m-%d %H:%M:%S')"
          #git push --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
      - 
        name: 发布 
        uses: softprops/action-gh-release@v2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
           > ### ![](https://img.shields.io/badge/%E7%BC%96%E8%AF%91%E6%97%B6%E9%97%B4-${{ env.build_time }}-8267?logo=github&labelColor=%E9%A1%BB)![](https://img.shields.io/github/downloads/${{ github.repository }}/${{ needs.check.outputs.ver }}/total?label=%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&logo=github) 

           ##
           
           **密钥存储位置已改为：`/etc/storage/tailscale/lib/tailscaled.state`适用于Padavan路由器**

           ##
           
           ### **各版本区别**
           - **常规版**：`tailscale` 和 `tailscaled` 其中`tailscale.txt`和`tailscaled.txt` 为其MD5校验值

           - **迷你版**：`tailscaled_full`  其中`tailscaled_full.txt` 为其MD5校验值

           - **精简版**：`tailscale_lite`和`tailscaled_lite` 其中`tailscale_lite.txt`和`tailscaled_lite.txt` 为其MD5校验值

           - **服务器**：`derper`自建中继服务器，其中`derper.txt`为其MD5校验值

           ##
           
           **迷你版需要改名为`tailscaled` 并用命令`ln -sf tailscaled tailscale` 软链接出`tailscale`子程序**
           **迷你版是将两个程序集中在一个二进制里面使用软链接分出子程序**
           
           **[精简版为省略调试信息和较少使用的功能等内容](https://tailscale.com/kb/1207/small-tailscale/)**
           <details>  <summary>精简掉的功能:</summary>

           - `ts_omit_aws`：不编译 AWS 相关功能。
           - `ts_omit_bird`：不编译 BIRD（BGP Daemon）。
           - `ts_omit_tap`：不编译 TUN/TAP 设备支持。
           - `ts_omit_kube`：不编译 Kubernetes 相关功能。
           - `ts_omit_completion`：不编译 Shell 自动补全功能。
           - `ts_omit_ssh`：不编译 Tailscale SSH 相关功能。
           - `ts_omit_wakeonlan`：不编译 Wake-on-LAN 相关功能。
           - `ts_omit_capture`：不编译流量捕获相关功能。

           </details>
           
           **[官方更新说明](https://github.com/tailscale/tailscale/releases)**
           
          tag_name: ${{ needs.check.outputs.ver }}
          files: |
              /opt/tainomal/tailscale
              /opt/tainomal/tailscale.txt
              /opt/tainomal/tailscaled
              /opt/tainomal/tailscaled.txt
              /opt/tainomal/derper
              /opt/tainomal/derper.txt
              /opt/taifull/tailscaled_full
              /opt/taifull/tailscaled_full.txt
              /opt/tailite/tailscale_lite
              /opt/tailite/tailscale_lite.txt
              /opt/tailite/tailscaled_lite
              /opt/tailite/tailscaled_lite.txt

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
     
  keepalive-workflow:
    # github超过60天未提交将自动停止工作流
    name: 工作流保活 
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      #- uses: gautamkrishnar/keepalive-workflow@v2
        #with:
          #use_api: true
      - name: 检查上次提交日期
        id: check_commit_date
        run: |
          # 获取上次提交日期（格式：YYYY-MM-DD）
          LAST_COMMIT_DATE=$(git log -1 --format=%cd --date=short)
          echo "上次提交日期: $LAST_COMMIT_DATE"
          # 计算当前日期和上次提交日期的差值（单位：天）
          LAST_COMMIT_TIMESTAMP=$(date -d "$LAST_COMMIT_DATE" +%s)
          CURRENT_TIMESTAMP=$(date +%s)
          DIFF_DAYS=$(( (CURRENT_TIMESTAMP - LAST_COMMIT_TIMESTAMP) / 86400 ))
          echo "距离上次提交以来的天数: $DIFF_DAYS"
          echo "diff_days=$DIFF_DAYS" >> $GITHUB_ENV
      - name: 执行空提交
        if: ${{ env.diff_days > 50 }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # 创建空提交
          git commit --allow-empty -m "自动空提交，保持仓库活跃"
          git push
